[project]
name = "simlib"
version = "0.1.0"
description = "Dependencies for the buoy simulator"
requires-python = ">=3.13,<=3.14"
dependencies = [
    "cartopy>=0.25.0",
    "dask>=2026.7.1",
    "geopandas>=1.1.4",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "haversine>=2.9.0",
    "matplotlib>=3.10.9",
    "modules>=1.0.0",
    "netcdf4>=1.7.3",
    "numpy>=2.2.6",
    "pyproj>=3.7.1",
    "seaborn>=0.13.2",
    "trio>=0.33.0",
    "xarray>=2025.6.1",
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
 
