[project]
name = "nsf-senior-thesis"
version = "0.1.0"
description = "Code for my senior thesis"
readme = "README.md"
requires-python = ">=3.13,<=3.14"
dependencies = [
    "basemap-data>=2.0.0",
    "cartopy>=0.25.0",
    "cftime>=1.6.5",
    "cytoolz>=1.1.0",
    "dask>=2026.6.0",
    "dask-jobqueue>=0.9.0",
    "geopandas>=1.1.4",
    "geoxarray>=0.2.0",
    "joblib>=1.5.3",
    "matplotlib>=3.10.9",
    "mpi4py>=4.1.2",
    "narwhals>=2.22.1",
    "netcdf4>=1.7.3",
    "numpy>=2.2.6",
    "polar>=0.0.127",
    "pyproj>=3.7.1",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "trio>=0.33.0",
    "xarray>=2025.6.1",
]

[dependency-groups]
dev = [
    "marimo>=0.23.11",
    "pydantic>=2.13.4",
    "python-lsp-ruff>=2.3.1",
    "python-lsp-server>=1.14.0",
    "ruff>=0.15.20",
]

[tool.pylsp.plugins.pycodestyle]
#ignore = ["E501"]
#enabled = false

[tool.pylsp.plugins.mccabe]
enabled = false

[tool.pylsp.plugins.pyflakes]
enabled = false

[tool.pylsp.plugins.pylsp_mypy]
enabled = true

[tool.pylsp.plugins.ruff]
enabled = true
lineLength = 100
