[project]
name = "buoysimulator"
version = "0.1.0"
description = "Buoy simulator code"
readme = "README.md"
requires-python = ">=3.13,<=3.14"
dependencies = [
    "altair>=6.2.2",
    "basemap-data>=2.0.0",
    "beautifulsoup4>=4.15.0",
    "cartopy>=0.25.0",
    "cftime>=1.6.5",
    "cytoolz>=1.1.0",
    "dask>=2026.6.0",
    "dask-jobqueue>=0.9.0",
    "geopandas>=1.1.4",
    "geopy>=2.4.1",
    "geoxarray>=0.2.0",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "haversine>=2.9.0",
    "joblib>=1.5.3",
    "lxml>=6.1.1",
    "matplotlib>=3.10.9",
    "modules>=1.0.0",
    "mpi4py>=4.1.2",
    "narwhals>=2.22.1",
    "netcdf4>=1.7.3",
    "numba>=0.66.0",
    "numpy>=2.2.6",
    "polar>=0.0.127",
    "pyarrow>=24.0.0",
    "pyproj>=3.7.1",
    "rich>=15.0.0",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "termcolor>=3.3.0",
    "tqdm>=4.68.3",
    "trio>=0.33.0",
    "vegafusion>=2.0.3",
    "viztracer>=1.1.1",
    "vl-convert-python>=1.9.0.post1",
    "xarray>=2025.6.1",
]

[project.scripts]
simulator = "simulator.main:main"

[tool.setuptools]
packages = [
    "simulator",
    "simlib",
    "simlib.core",
    "simlib.tools"
]

[dependency-groups]
dev = [
    "marimo>=0.23.11",
    "pydantic>=2.13.4",
    "python-lsp-ruff>=2.3.1",
    "python-lsp-server>=1.14.0",
    "ruff>=0.15.20",
]
